substitutions:
  _IMAGE_NAME: prod-centos7-javaapp-v1-image
  _PROJECT_ID: searce-playground
  _IMAGE_FAMILY: centos-7
  _REGION: asia-south1
  _IMAGE_ZONE: asia-south1-b
  _MACHINE_TYPE: n1-standard-2
  _NETWORK: packer-vpc
  _SUBNETWORK: packer-subnet

steps:
- name: 'maven'
  entrypoint: 'mvn'
  args: ['clean']

- name: 'maven'
  entrypoint: 'mvn'
  args: ['package']

- name: 'gcr.io/${_PROJECT_ID}/packer'
  args:
  - build
  - -var
  - image_name=${_IMAGE_NAME}-$SHORT_SHA
  - -var
  - project_id=${_PROJECT_ID}
  - -var
  - image_family=${_IMAGE_FAMILY}
  - -var
  - image_zone=${_IMAGE_ZONE}
  - -var
  - zone=${_IMAGE_ZONE}
  - -var
  - region=${_REGION}
  - -var
  - source_image_family=${_IMAGE_FAMILY}
  - -var
  - network=${_NETWORK}
  - -var
  - subnetwork=${_SUBNETWORK}
  - -var
  - machine_type=${_MACHINE_TYPE}
  - packer.json

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'gcloud'
  args:
  - beta
  - compute
  - --project=${_PROJECT_ID}
  - instance-templates
  - create
  - java-packer-template-$SHORT_SHA
  - --image=prod-centos7-javaapp-v1-image-$SHORT_SHA
  - --machine-type=${_MACHINE_TYPE}
  - --network=projects/searce-playground/global/networks/default
  - --network-tier=PREMIUM
  - --maintenance-policy=MIGRATE

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'gcloud'
  args:
  - compute
  - instance-groups
  - --project=${_PROJECT_ID}
  - managed
  - rolling-action
  - start-update
  - java-packer-mig
  - --version
  - template=java-packer-template-$SHORT_SHA
  - --type=proactive
  - --force
  - --max-surge=1
  - --max-unavailable=1
  - --replacement-method=substitute
  - --zone=us-east1-d
